project_id=ambient-cubist-384700

git clone https://github.com/GoogleCloudPlatform/cluster-toolkit.git
cd cluster-toolkit/
make
./gcluster --version

git clone https://github.com/solanki-ravi/gp2demo.git
cd gp2demo

./gcluster create hpc-slurm.yaml \
    -l ERROR --vars project_id=$project_id

# use the appropriate directory name generated by the create command
./gcluster deploy hpc-slurm-gpt2demo-gpu-g2-deepspeed

# ssh to the head node
# gcloud compute ssh head-0 --zone=us-central1-a

# run a command on the head node
srun -N 3 hostname

# destroy the cluster
./gcluster destroy hpc-slurm-gpt2demo --auto-approve
